---
# tasks file for dnsmasq
- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: Remove default /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Create new /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: touch

- name: Fill /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'
    create: yes

- name: Install dnsmasq
  apt:
    name: dnsmasq
    state: present
    update_cache: yes

