---
# tasks file for nginx_php
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install php-fpm
  apt:
    state: present
    pkg:
    - php7.4 
    - php7.4-cli
    - php7.4-fpm
    - php7.4-json
    - php7.4-pdo
    - php7.4-mysql
    - php7.4-zip 
    - php7.4-gd
    - php7.4-mbstring
    - php7.4-curl
    - php7.4-xml
    - php-pear 
    - php7.4-bcmath

- name: Start service php7.4-fpm
  service:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Create site directory
  file: 
    path:  /opt/nginx/ansible
    state: directory

- name: create index.php
  file:
    path: /opt/nginx/ansible/index.php
    state: touch

- name: Create index.php
  lineinfile:
    path: /opt/nginx/ansible/index.php
    line: '<?php phpinfo();?>'
    create: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Add new default site
  copy:
    src: /etc/ansible/roles/nginx_phpfpm/files/localhost
    dest: /etc/nginx/sites-available/default
    remote_src: yes
  notify: reload_nginx