---
# tasks file for nginx_php
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Install php-fpm
  apt:
    state: present
    pkg:
    - php7.4 
    - php7.4-cli
    - php7.4-fpm
    - php7.4-json
    - php7.4-pdo
    - php7.4-mysql
    - php7.4-zip 
    - php7.4-gd
    - php7.4-mbstring
    - php7.4-curl
    - php7.4-xml
    - php-pear 
    - php7.4-bcmath

- name: Start service php7.4-fpm
  service:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Add .php to index
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: 'index index.html index.htm index.nginx-debian.html;'
    insertafter: '^index index.html index.htm index.nginx-debian.html;'
    line: 'index index.php'
    state: present

- name: Add .php to index
  lineinfile:
    dest: /etc/nginx/sites-available/default
    regexp: 'server_name _;'
    insertafter: 'server_name _;'
    line: '
    server_name _;
    location ~ \.php$ {
      fastcgi_pass unix:/run/php/php7.4-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include /etc/nginx/fastcgi_params;
    }
    '
    state: present

- name: Start service nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: create index.php
  file:
    path: /var/www/html/index.php
    state: touch

- name: Create index.php
  lineinfile:
    path: /var/www/html/index.php
    line: '<?php phpinfo();?>'
    create: yes